### ISSUE TITLE
Could you add PHP 4 docker file?

### ISSUE THREAD

**Issue by johnnyzheng99** [cmfatih/dockerhub#4]
It seems the PHP 4 docker repo is in docker registry but not in github. Is it possible you can also send it git? Currently running your php 4 docker, it shows the following error:

```
#!sh
Usage: /usr/local/apache2/bin/httpd [-D name] [-d directory] [-f file]
                                    [-C "directive"] [-c "directive"]
                                    [-k start|restart|graceful|stop]
                                    [-v] [-V] [-h] [-l] [-L] [-t] [-S]
....
```

**Comment by cmfatih** [comment]
Where is the error?

Have you tried `docker run -d -p 10080:80 cmfatih/php4 /usr/local/apache2/bin/apachectl -D FOREGROUND` It works for me

![docker-php4](https://cloud.githubusercontent.com/assets/965295/7184628/605bd81a-e42c-11e4-931a-71971882ae57.png)

P.S. : There is no Dockerfile for this container because I built it manually from scratch. Building process can't (it is very hard) be done with Dockerfiles

**Comment by johnnyzheng99** [comment]
Thanks for your prompt reply. Yes, it's working now. Sorry I forgot the -D FOREGROUND parameter.

I will try -v /path/in/host:/var/www and add a site to see how it works. PHP 4 is terrible but a project has to be done over it. :(

**Comment by cmfatih** [comment]
fyi: apache looks for `/usr/local/apache2/htdocs` in container. So probably you should use `/path/in/host:/usr/local/apache2/htdocs`

**Comment by johnnyzheng99** [comment]
Nice! Thanks for your hint.
